print('hello 6/14')
print('patchanida')
print('payaramp')
print('07 december2004')
print('17')
print('167')
print('52')
print('bubuzen')
print('bubu mommy')
print('kirishima eijiro')
print('chonrasadonumrung school')